import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import Navbar from "@/components/navbar"
import "@/styles/globals.css";

const oswald = Oswald({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
